%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
# Camera calibration and distortion parameters (OpenCV) 
model_type: scaramuzza
camera_name: camera
image_width: 1280
image_height: 720
poly_parameters: 
  p0: -3.223972e+02
  p1: 0.000000e+00
  p2: 9.374996e-04
  p3: -8.625960e-07
  p4: 1.405495e-09
inv_poly_parameters:  
  p0: 592.129259
  p1: 432.150057
  p2: -6.831151
  p3: 4.763648
  p4: 79.939565
  p5: -3.543728
  p6: -79.136807
  p7: -16.888823
  p8: 41.111397
  p9: 27.820739
  p10: 5.332581 

affine_parameters:
  ac: 1.000029
  ad: 0.002053
  ae: 0.000928
  cx: 630.642288
  cy: 367.633193

# Camera frames per second 
Camera.fps: 30.0

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 3000

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 25
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.1
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 1
Viewer.PointSize: 2
Viewer.CameraSize: 0.15
Viewer.CameraLineWidth: 2
Viewer.ViewpointX: 0
Viewer.ViewpointY: -10
Viewer.ViewpointZ: -0.1
Viewer.ViewpointF: 2000

Map.mapfile: /home/hawk/Documents/trace_data/mapfile/map.bin

