%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
# Camera calibration and distortion parameters (OpenCV) 
model_type: scaramuzza
camera_name: camera
image_width: 1280
image_height: 720
poly_parameters: 
  p0: -3.275053e+02
  p1: 0.000000e+00
  p2: 1.039733e-03
  p3: -1.229119e-06
  p4: 1.787320e-09
inv_poly_parameters:  
  p0: 591.012736
  p1: 417.086067
  p2: -25.524614
  p3: 8.639673
  p4: 80.899486
  p5: -44.879909
  p6: -70.502411
  p7: 161.708831
  p8: 309.434387
  p9: 212.623410
  p10: 68.734146
  p11: 8.786598
affine_parameters:
  ac: 1.000854
  ad: -0.000045
  ae: 0.001593
  cx: 648.593619
  cy: 362.181839

# Camera frames per second 
Camera.fps: 25.0

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 3000

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.1
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 1
Viewer.PointSize: 2
Viewer.CameraSize: 0.15
Viewer.CameraLineWidth: 2
Viewer.ViewpointX: 0
Viewer.ViewpointY: -10
Viewer.ViewpointZ: -0.1
Viewer.ViewpointF: 2000

Map.mapfile: /home/firecloudy/yh-avp/catkin_ws_avp_hld/vslam_map/map.bin

